/**
 * CONTENT EDITING GUIDE
 * ---------------------
 * Open this file in Visual Studio Code to change all visible portfolio content.
 * Edit `de` for German and `en` for English. Keep the object keys unchanged.
 * Project cards use `projects.platform` and `projects.cases`; their documentation
 * appears under `caseStudies` and is linked with static-safe #case-... anchors.
 */

export type Language = "de" | "en";

const sharedStack = ["Kali Linux", "Wazuh", "Metasploitable 2", "Metasploitable 3", "VMware", "Windows 10 / 11"];

export const portfolioContent = {
  de: {
    languageName: "Deutsch",
    languageSwitchLabel: "Sprache auswählen",
    navigation: { projects: "Projekte", profile: "Profil", skills: "Skills", learning: "Lernweg", contact: "Kontakt", github: "GitHub" },
    brandBackToTop: "Marco Lütkemüller — zurück nach oben",
    menuOpen: "Navigation öffnen",
    menuClose: "Navigation schließen",
    hero: {
      eyebrow: "ANGEHENDER SOC ANALYST / FACHINFORMATIKER FÜR SYSTEMINTEGRATION",
      titleLines: ["Aufbauen.", "Erkennen.", "Dokumentieren."],
      intro: "Marco Lütkemüller verbindet Systemintegration, Netzwerkadministration und praxisnahe Detection-Experimente zu nachvollziehbaren Security-Operations-Use-Cases.",
      inspect: "Case Studies ansehen",
      github: "GitHub ansehen",
      imageLabel: "Abstrakte SOC-Homelab-Arbeitsumgebung",
      stackLabel: "Homelab-Stack",
      telemetry: { title: "HOMELAB / SCOPE", source: "TELEMETRIE", sourceValue: "Windows Event Logs", siem: "ANALYSE", siemValue: "Wazuh SIEM", lab: "LAB", labValue: "VMware · isoliert", mode: "MODUS", modeValue: "kontrollierte Tests" },
    },
    stack: sharedStack,
    profile: {
      marker: "About Me",
      statement: "Infrastruktur wird zur Detection-Grundlage, wenn Identitäten, Endpoints und Netzwerkverkehr gemeinsam lesbar werden.",
      body: "Ich bin Fachinformatiker für Systemintegration mit praktischer Erfahrung in Routing, Switching, Firewall- und VPN-Betrieb, Windows- und Active-Directory-Administration sowie VMware-Virtualisierung. Mein Schwerpunkt verschiebt diese Basis gezielt in Richtung Blue Team: Log-Analyse, Detection Engineering und Incident-Response-Workflows.",
      facts: [["PROFIL", "Angehender SOC Analyst"], ["BASIS", "Systemintegration & Netzwerke"], ["METHODE", "Aufbauen / Beobachten / Iterieren"]],
      capabilities: ["TCP/IP · VLAN · DNS · DHCP · NAT", "Active Directory · GPO · Rollenmodelle", "Router · Switches · Firewalls · VPN", "VMware · Security Labs · Vulnerability Scanning", "2nd-Level-Support · Dokumentation · Betrieb"],
    },
    projects: {
      marker: "Detection Case Studies",
      heading: ["Infrastruktur als", "Beweisgrundlage."],
      intro: "Die SIEM-Implementierung liefert die Plattform. Die Case Studies zeigen, wie aus Telemetrie testbare Detection- und Triage-Abläufe werden.",
      platformLabel: "Plattform / Homelab",
      casesLabel: "Dokumentierte Use Cases",
      walkthrough: "Case Study öffnen",
      repository: "Repository",
      platform: { title: "Room 00 · Aufbau des Purple-Team-Labors", summary: "Der dokumentierte Aufbau einer isolierten Security-Laborumgebung mit Active Directory, Linux-Multifunktionsserver, Kali-Angriffsplattform und zentralem Wazuh-Monitoring.", tags: ["Room 00", "Active Directory", "Wazuh", "Kali Linux", "VMware", "RedTeamLab"], state: "Aktiver Aufbau", target: "#case-siem-implementation" },
      cases: [
        { id: "ad-lateral-movement", title: "Active Directory Lateral Movement", summary: "Lateral-Movement-Techniken in einer Active-Directory-Umgebung mit Wazuh und Windows-Ereignisprotokollen erkennen und einordnen.", tags: ["Wazuh", "Active Directory", "Event ID 4624", "Event ID 4688", "Event ID 4769"], state: "Abgeschlossen", date: "Januar 2026" },
        { id: "network-discovery", title: "Network Discovery Monitoring", summary: "Netzwerkerkundung, Port-Scans und Service-Enumeration als beobachtbares Verhalten modellieren und mit Detection-Logik verknüpfen.", tags: ["Kali Linux", "Wazuh", "Wireshark", "Network Monitoring"], state: "Dokumentiert", date: "Dezember 2025" },
        { id: "brute-force", title: "Brute Force Attack Detection", summary: "Wiederholte Authentifizierungsversuche gegen SSH, RDP und Web-Anwendungen über Log- und Verhaltensmuster erkennen.", tags: ["SSH", "RDP", "Log Analysis", "Triage"], state: "Dokumentiert", date: "November 2025" },
        { id: "powershell", title: "Suspicious PowerShell Activity", summary: "Verdächtige PowerShell-Ausführung, Encoded Commands und auffällige Modulnutzung als Endpoint-Detection-Use-Case erfassen.", tags: ["PowerShell", "Windows Event Logs", "Endpoint Detection", "Wazuh"], state: "Dokumentiert", date: "Oktober 2025" },
        { id: "ransomware", title: "Ransomware Behavior Detection", summary: "Dateiverschlüsselung, Registry-Änderungen und ungewöhnliche Netzwerkkommunikation als verhaltensbasierte Detection-Signale prüfen.", tags: ["Behavioral Detection", "Windows", "Network Monitoring", "Incident Response"], state: "Dokumentiert", date: "September 2025" },
      ],
    },
    skills: {
      marker: "Kompetenzprofil",
      heading: ["Operative Basis,", "sichtbar gemacht."],
      intro: "Kompetenzen aus Berufspraxis, Systemintegration und aktivem Security-Learning.",
      note: "Die Indikatoren zeigen den aktuellen Portfolio-Fokus. Entscheidend sind belastbare Umgebungen, saubere Dokumentation und wiederholbare Abläufe — nicht isolierte Tool-Namen.",
      status: "AKTIVER STATUS",
      active: "Praxis & Aufbau",
      items: [["Security Operations", "SIEM · Log-Analyse · Detection · Triage", 82], ["Windows & Active Directory", "GPO · Rollen · Endpoint Visibility", 88], ["Netzwerke & Firewall", "VLAN · VPN · DNS · Paket-Analyse", 90], ["Virtualisierung", "VMware · Lab-Architektur · Server", 86], ["Linux & Security Labs", "Kali · Wazuh · Vulnerability Scanning", 79], ["Automation & Dokumentation", "PowerShell · technische Dokumentation", 76]],
    },
    learning: {
      marker: "Learning Journey",
      heading: ["Lernen als", "nachvollziehbarer Pfad."],
      intro: "Qualifikationen und Trainings, aus denen die aktuelle SOC-Ausrichtung entsteht.",
      items: [
        { date: "01 / 2026", status: "Abgeschlossen", title: "Fachinformatiker für Systemintegration (IHK)", detail: "Umschulung bei cadata Bildungs GmbH; IHK-Abschlussprüfung erfolgreich bestanden." },
        { date: "Q1 / 2026", status: "Abgeschlossen", title: "TryHackMe Pre-SOC", detail: "Grundlagenorientiertes SOC-Training mit praktischen Security-Lab-Übungen." },
        { date: "Q1 / 2026", status: "Abgeschlossen", title: "SOC101 Course", detail: "Security-Operations-Center-Grundlagen mit Fokus auf Monitoring, Detection und Response." },
        { date: "IN VORBEREITUNG", status: "Geplant", title: "CompTIA Network+", detail: "Netzwerkanalyse, Protokollhierarchien und Troubleshooting als Vertiefung der operativen Basis." },
      ],
    },
    caseStudies: [
      { id: "siem-implementation", kind: "Room 00 · Laboraufbau", title: "Room 00 · Aufbau des Purple-Team-Labors", lead: "Room 00 dokumentiert den Aufbau der isolierten Security-Laborumgebung: von der Netzwerkverbindung über die Zielsysteme bis zur zentralen Wazuh-Monitoring-Umgebung.", environment: ["VMware Workstation Pro mit VMnet0 im Bridged-Modus", "RedTeamLab-Netz 192.168.42.0/24", "Opferumgebung: DC01, Alice-PC und Bob-PC", "Angreifer-/Security-Testing-System: Kali Linux auf dem Laptop", "Wazuh-Server als zentrale Monitoring-Plattform"], scenarioTitle: "Aufbau", scenario: "Die Umgebung verbindet eine Active-Directory-Zielumgebung, einen Linux-Multifunktionsserver, eine Kali-Angriffsplattform und eine zentrale Wazuh-Monitoring-Umgebung. Room 00 endet mit dem vollständigen Golden-Baseline-Prüfprotokoll.", methodTitle: "Prüfprotokoll", method: "Geprüft werden VMware-Zuordnung, VM-Status, Netzwerk, Konnektivität, DNS, Active Directory, Serverdienste, Wazuh, Zeit-Synchronisation und die Netzwerk-Exposure-Baseline.", findingsTitle: "Abschluss", findings: "Die Golden Baseline bildet den bestätigten Referenzzustand des Labors. Für spätere Purple-Team-Fälle stehen damit nachvollziehbare Systeme, Adressen, Dienste und Telemetriequellen zur Verfügung.", lessons: ["Opfer- und Angreiferseite werden im Labor nachvollziehbar getrennt.", "Die Netzwerk- und Systemprüfung bildet die Grundlage für reproduzierbare Szenarien.", "Wazuh, Sysmon, Windows Event Logs und Linux-Logs liefern die Telemetrie-Basis."], tools: ["VMware Workstation Pro", "VMnet0 · Bridged", "Active Directory", "Kali Linux", "Wazuh", "Debian 13"] },
      { id: "ad-lateral-movement", kind: "Blue Team Case Study", title: "Active Directory Lateral Movement Detection", lead: "Lateral-Movement-Techniken in einer Active-Directory-Umgebung mit Wazuh SIEM und Windows-Ereignisprotokollen erkennen und einordnen.", environment: ["Windows Server 2019 als Domain Controller", "3× Windows-10-Clients", "Kali Linux als Angriffssystem", "Wazuh SIEM und Splunk Forwarder"], scenarioTitle: "Szenario", scenario: "Ein kontrollierter Angriffspfad untersucht Pass-the-Hash und Kerberoasting als Techniken zur Privilegienausweitung und lateralen Bewegung.", methodTitle: "Detection-Methode", method: "Windows Security Event ID 4624, 4688 und 4769 korrelieren, um auffällige Netzwerk-Anmeldungen, Prozessstarts und Kerberos-TGS-Anfragen einzuordnen.", findingsTitle: "Evidenz", findings: "Der Use Case verbindet Authentifizierungs-, Prozess- und Kerberos-Telemetrie zu einer belastbaren Triage-Grundlage statt auf ein einzelnes Event zu vertrauen.", lessons: ["Kerberos-TGS-Anfragen auf ungewöhnliche Verschlüsselung und Service-Accounts prüfen.", "Prozesserstellung bekannter Angriffswerkzeuge mit Kontext bewerten.", "Mehrere Event-Typen korrelieren und eine Baseline als Vergleich nutzen."], tools: ["Wazuh", "Windows Event Viewer", "Splunk", "Wireshark", "PowerShell"] },
      { id: "network-discovery", kind: "Detection Engineering Case Study", title: "Network Discovery Monitoring", lead: "Netzwerkerkundung als Verhalten erfassen: Port-Scans, Service-Enumeration und Netzwerkkartierung werden zu prüfbaren Detection-Signalen.", environment: ["Kali Linux für kontrollierte Discovery-Simulationen", "Windows- und Linux-Endpoints", "Wazuh und Netzwerk-Telemetrie", "Wireshark für Paket- und Kontextanalyse"], scenarioTitle: "Szenario", scenario: "Eine kontrollierte Erkundungsphase erzeugt wiederholbare Netzwerkaktivität, die sich von normalem Betrieb abgrenzen lässt.", methodTitle: "Detection-Methode", method: "Zeitliche Häufung, Zielbreite und Port-Muster als Kontext für Netzwerkerkundung prüfen und mit Endpoint- oder Netzwerkdaten anreichern.", findingsTitle: "Evidenz", findings: "Der Use Case zeigt, dass die Qualität einer Detection nicht nur von einer Regel, sondern von Kontext, Baseline und Triage-Notizen abhängt.", lessons: ["Port-Muster und Zielbreite gemeinsam bewerten.", "Regulären Admin-Verkehr in die Baseline aufnehmen.", "Paketanalyse als Ergänzung zur Log-Telemetrie nutzen."], tools: ["Kali Linux", "Wazuh", "Wireshark", "Network Monitoring"] },
      { id: "brute-force", kind: "Blue Team Case Study", title: "Brute Force Attack Detection", lead: "Wiederholte Anmeldeversuche gegen SSH, RDP und Web-Anwendungen über Log- und Verhaltensmuster erkennen und priorisieren.", environment: ["SSH-, RDP- und Web-Authentifizierungsquellen", "Zentrale Log-Aggregation", "Wazuh für Analyse und Alerting", "Triage-Notizen für Wiederholungsfälle"], scenarioTitle: "Szenario", scenario: "Mehrere fehlgeschlagene Authentifizierungen werden als kontrollierter Testfall erzeugt und gegen reguläre Fehlerbilder abgegrenzt.", methodTitle: "Detection-Methode", method: "Fehlversuche, Zeitfenster, Quell- und Zielbeziehungen sowie mögliche Erfolgsmeldungen korrelieren.", findingsTitle: "Evidenz", findings: "Ein guter Brute-Force-Use-Case trennt fehlerhafte Anmeldung, Passwortspray und potenziell erfolgreiche Übernahme anhand des Verlaufs.", lessons: ["Fehlversuche und erfolgreiche Folgelogins zusammen betrachten.", "Zeitfenster und Quellbeziehung als Priorisierung nutzen.", "Service-Accounts und administrative Prozesse als Sonderfälle dokumentieren."], tools: ["Wazuh", "SSH", "RDP", "Log Analysis"] },
      { id: "powershell", kind: "Endpoint Detection Case Study", title: "Suspicious PowerShell Activity", lead: "Verdächtige PowerShell-Ausführung mit Encoded Commands, auffälliger Modulnutzung und Prozesskontext als Endpoint-Use-Case bewerten.", environment: ["Windows-Endpoints mit PowerShell", "Windows Event Logs", "Wazuh für zentrale Telemetrie", "Kali Linux für kontrollierte Tests"], scenarioTitle: "Szenario", scenario: "PowerShell-Aktivität wird anhand von Prozesskette, Argumenten und Ausführungskontext untersucht.", methodTitle: "Detection-Methode", method: "Kodierte Argumente, ungewöhnliche Parent-Child-Beziehungen und verdächtige Module als zusammengesetzte Signale bewerten.", findingsTitle: "Evidenz", findings: "Die Bewertung gewinnt an Qualität, wenn Prozesskontext und Benutzerbezug zusammen mit dem Kommando berücksichtigt werden.", lessons: ["Encoded Commands nicht isoliert bewerten.", "Prozesskette und Ausführungskontext dokumentieren.", "Legitime Administration in die Baseline einbeziehen."], tools: ["PowerShell", "Windows Event Logs", "Wazuh", "Endpoint Detection"] },
      { id: "ransomware", kind: "Threat Detection Case Study", title: "Ransomware Behavior Detection", lead: "Dateiverschlüsselung, Registry-Änderungen und ungewöhnliche Netzwerkkommunikation als verhaltensbasierte Detection-Signale prüfen.", environment: ["Windows-Endpoints", "Zentrale Log- und Endpoint-Telemetrie", "Netzwerkmonitoring", "Incident-Response-Notizen"], scenarioTitle: "Szenario", scenario: "Ein verhaltensbasierter Übungsrahmen verbindet Veränderungen auf Endpoint- und Netzwerkebene zu einer Untersuchungshypothese.", methodTitle: "Detection-Methode", method: "Dateiaktivität, Registry-Spuren, Prozesskontext und ausgehende Kommunikation auf verdächtige Kombinationen prüfen.", findingsTitle: "Evidenz", findings: "Verhaltensbasierte Detection wird belastbarer, wenn mehrere schwache Signale zu einem zeitlichen Ablauf verbunden werden.", lessons: ["Datei-, Prozess- und Netzwerkspuren korrelieren.", "Triage-Schritte als Teil des Use Cases dokumentieren.", "Wiederherstellungs- und Eskalationswege früh mitdenken."], tools: ["Windows", "Network Monitoring", "Incident Response", "Behavioral Detection"] },
    ],
    writing: {
      marker: "Lab-Notizen",
      heading: ["Notizen von der", "Lab-Bank."],
      intro: "Technische Beiträge, die Experimente in wiederverwendbares Betriebswissen überführen.",
      items: [{ type: "Lab-Notiz / 01", title: "Telemetrie entwerfen, die auch morgen noch nützlich ist", description: "Ein praxisnaher Blick auf Logquellen, Signalqualität und die Gewohnheit, den Zweck eines Alerts zu dokumentieren.", readTime: "6 Min. Lesezeit" }, { type: "Detection-Brief / 02", title: "Von der ATT&CK-Technik zur testbaren Detection", description: "Ein strukturierter Ablauf, um aus einer Verhaltenshypothese eine wiederholbare Homelab-Übung zu machen.", readTime: "8 Min. Lesezeit" }, { type: "Build-Log / 03", title: "Kleine SOC-Labs brauchen klare Grenzen", description: "Notizen zu Segmentierung, Verantwortlichkeiten und einer Infrastruktur, die sich einfacher untersuchen lässt.", readTime: "5 Min. Lesezeit" }],
    },
    contact: {
      eyebrow: "OFFEN FÜR TECHNISCHE GESPRÄCHE",
      heading: ["Systeme sichtbar", "sicherer machen?"],
      body: "Ich freue mich über Gespräche zu Systemintegration, Security Operations und Junior-SOC-Analyst-Rollen. Alternativ kannst du die Case Studies auf GitHub ansehen oder den Portfolio-Lebenslauf laden.",
      github: "GitHub-Profil", linkedin: "LinkedIn-Profil", cv: "Portfolio-CV laden", formTitle: "KONTAKT / NEUE NACHRICHT", name: "Name", email: "E-Mail", message: "Nachricht", namePlaceholder: "Dein Name", emailPlaceholder: "du@unternehmen.de", messagePlaceholder: "Was möchtest du besprechen?", submit: "Nachricht senden", sending: "Wird gesendet …", sent: "Danke. Deine Nachricht wurde erfolgreich versendet.", failed: "Der Versand konnte nicht abgeschlossen werden. Bitte versuche es erneut oder nutze LinkedIn.", setup: "Formspree ist noch nicht verbunden. Trage die Form-ID in client/src/config/siteConfig.ts ein.", privacy: "Mit dem Absenden werden die Formulardaten über Formspree verarbeitet.", mailSubjectPrefix: "Portfolio-Anfrage von", mailBodyName: "Name", mailBodyEmail: "E-Mail", location: "Deutschland · NRW · Metropol Ruhr-Region",
    },
    footer: { trace: "Signal Trace / SOC Portfolio", back: "Nach oben" },
    terminal: {
      title: "SOC://OPERATOR-SHELL", interactive: "INTERAKTIV", prompt: "marco@soc-lab:~$", placeholder: "Versuche: about", available: "Befehle", soundOn: "Sound an", soundOff: "Sound aus", greeting: ["[system] SOC-Lab-Operator verbunden.", "Tippe `about`, `stack`, `projects`, `contact`, `help` oder `clear`."], unknown: "Befehl nicht gefunden. Tippe `help`, um alle Befehle zu sehen.",
      commands: { about: ["Marco Lütkemüller // Angehender SOC Analyst.", "Basis: Systemintegration, Netzwerke, Windows und Active Directory."], stack: ["Kali Linux · Wazuh · Metasploitable 2/3 · VMware · Windows 10/11", "Status: lab://active"], projects: ["Tracks: SIEM-Implementierung + 5 dokumentierte Detection Case Studies."], contact: ["GitHub, LinkedIn oder Kontaktbereich öffnen für technische Gespräche."], help: ["about — kurze Vorstellung", "stack — Homelab-Stack", "projects — Case Studies", "contact — Kontaktweg", "clear — Terminal leeren"] },
    },
  },
  en: {
    languageName: "English",
    languageSwitchLabel: "Select language",
    navigation: { projects: "Projects", profile: "Profile", skills: "Skills", learning: "Learning", contact: "Contact", github: "GitHub" },
    brandBackToTop: "Marco Lütkemüller — back to top", menuOpen: "Open navigation", menuClose: "Close navigation",
    hero: { eyebrow: "ASPIRING SOC ANALYST / SYSTEMS INTEGRATION SPECIALIST", titleLines: ["Build.", "Detect.", "Document."], intro: "Marco Lütkemüller connects systems integration, network administration, and hands-on detection experiments into traceable security operations use cases.", inspect: "Inspect case studies", github: "View GitHub", imageLabel: "Abstract SOC homelab workbench", stackLabel: "Homelab stack", telemetry: { title: "HOMELAB / SCOPE", source: "TELEMETRY", sourceValue: "Windows event logs", siem: "ANALYSIS", siemValue: "Wazuh SIEM", lab: "LAB", labValue: "VMware · isolated", mode: "MODE", modeValue: "controlled tests" } },
    stack: sharedStack,
    profile: { marker: "About Me", statement: "Infrastructure becomes a detection foundation when identities, endpoints, and network traffic are readable together.", body: "I am a systems integration specialist with practical experience in routing, switching, firewall and VPN operations, Windows and Active Directory administration, and VMware virtualisation. I am intentionally extending that foundation toward Blue Team work: log analysis, detection engineering, and incident-response workflows.", facts: [["PROFILE", "Aspiring SOC Analyst"], ["FOUNDATION", "Systems & Networks"], ["METHOD", "Build / Observe / Iterate"]], capabilities: ["TCP/IP · VLAN · DNS · DHCP · NAT", "Active Directory · GPO · role models", "Routers · switches · firewalls · VPN", "VMware · security labs · vulnerability scanning", "Second-level support · documentation · operations"] },
    projects: {
      marker: "Detection Case Studies", heading: ["Infrastructure as", "evidence."], intro: "The SIEM implementation provides the platform. The case studies show how telemetry becomes testable detection and triage workflows.", platformLabel: "Platform / Homelab", casesLabel: "Documented use cases", walkthrough: "Open case study", repository: "Repository",
      platform: { title: "Room 00 · Purple-Team Lab Foundation", summary: "A documented build of an isolated security lab with Active Directory, a Linux multifunction server, a Kali security-testing platform, and centralized Wazuh monitoring.", tags: ["Room 00", "Active Directory", "Wazuh", "Kali Linux", "VMware", "RedTeamLab"], state: "Active build", target: "#case-siem-implementation" },
      cases: [
        { id: "ad-lateral-movement", title: "Active Directory Lateral Movement", summary: "Detect and classify lateral movement techniques in an Active Directory environment using Wazuh and Windows event logs.", tags: ["Wazuh", "Active Directory", "Event ID 4624", "Event ID 4688", "Event ID 4769"], state: "Completed", date: "January 2026" },
        { id: "network-discovery", title: "Network Discovery Monitoring", summary: "Model network discovery, port scans, and service enumeration as observable behavior connected to detection logic.", tags: ["Kali Linux", "Wazuh", "Wireshark", "Network Monitoring"], state: "Documented", date: "December 2025" },
        { id: "brute-force", title: "Brute Force Attack Detection", summary: "Detect repeated authentication attempts against SSH, RDP, and web applications through log and behavioral patterns.", tags: ["SSH", "RDP", "Log Analysis", "Triage"], state: "Documented", date: "November 2025" },
        { id: "powershell", title: "Suspicious PowerShell Activity", summary: "Capture suspicious PowerShell execution, encoded commands, and unusual module use as an endpoint detection use case.", tags: ["PowerShell", "Windows Event Logs", "Endpoint Detection", "Wazuh"], state: "Documented", date: "October 2025" },
        { id: "ransomware", title: "Ransomware Behavior Detection", summary: "Assess file encryption, registry modification, and unusual network communication as behavioral detection signals.", tags: ["Behavioral Detection", "Windows", "Network Monitoring", "Incident Response"], state: "Documented", date: "September 2025" },
      ],
    },
    skills: { marker: "Capability map", heading: ["Operational foundation,", "made visible."], intro: "Capabilities from professional practice, systems integration, and active security learning.", note: "Indicators reflect the current portfolio focus. Their value is in resilient environments, clear documentation, and repeatable operating workflows — not isolated tool names.", status: "ACTIVE STATUS", active: "Practice & build", items: [["Security Operations", "SIEM · log analysis · detection · triage", 82], ["Windows & Active Directory", "GPO · roles · endpoint visibility", 88], ["Networks & Firewall", "VLAN · VPN · DNS · packet analysis", 90], ["Virtualisation", "VMware · lab architecture · servers", 86], ["Linux & Security Labs", "Kali · Wazuh · vulnerability scanning", 79], ["Automation & Documentation", "PowerShell · technical documentation", 76]] },
    learning: { marker: "Learning Journey", heading: ["Learning as a", "traceable path."], intro: "Qualifications and training that establish the current SOC direction.", items: [{ date: "01 / 2026", status: "Completed", title: "Systems Integration Specialist (IHK)", detail: "Reskilling with cadata Bildungs GmbH; IHK final examination successfully completed." }, { date: "Q1 / 2026", status: "Completed", title: "TryHackMe Pre-SOC", detail: "Foundational SOC training with hands-on security lab exercises." }, { date: "Q1 / 2026", status: "Completed", title: "SOC101 Course", detail: "Security operations centre fundamentals focused on monitoring, detection, and response." }, { date: "IN PROGRESS", status: "Planned", title: "CompTIA Network+", detail: "Network analysis, protocol hierarchies, and troubleshooting to deepen the operational foundation." }] },
    caseStudies: [
      { id: "siem-implementation", kind: "Room 00 · Lab foundation", title: "Room 00 · Purple-Team Lab Foundation", lead: "Room 00 documents the build of an isolated security lab: from the network connection and target systems to the centralized Wazuh monitoring environment.", environment: ["VMware Workstation Pro with VMnet0 in bridged mode", "RedTeamLab network 192.168.42.0/24", "Victim environment: DC01, Alice-PC, and Bob-PC", "Attacker / security-testing system: Kali Linux on the laptop", "Wazuh server as the central monitoring platform"], scenarioTitle: "Build", scenario: "The environment connects an Active Directory target environment, a Linux multifunction server, a Kali security-testing platform, and a central Wazuh monitoring environment. Room 00 ends with the complete Golden Baseline verification protocol.", methodTitle: "Verification protocol", method: "The protocol checks VMware assignments, VM status, networking, connectivity, DNS, Active Directory, server services, Wazuh, time synchronization, and the network exposure baseline.", findingsTitle: "Completion", findings: "The Golden Baseline defines the confirmed reference state of the lab. It provides traceable systems, addresses, services, and telemetry sources for later Purple-Team scenarios.", lessons: ["The victim and attacker sides are made explicit in the lab model.", "Network and system verification support reproducible scenarios.", "Wazuh, Sysmon, Windows event logs, and Linux logs form the telemetry foundation."], tools: ["VMware Workstation Pro", "VMnet0 · Bridged", "Active Directory", "Kali Linux", "Wazuh", "Debian 13"] },
      { id: "ad-lateral-movement", kind: "Blue Team case study", title: "Active Directory Lateral Movement Detection", lead: "Detect and classify lateral movement techniques in an Active Directory environment using Wazuh SIEM and Windows event logs.", environment: ["Windows Server 2019 domain controller", "3× Windows 10 clients", "Kali Linux attack system", "Wazuh SIEM and Splunk Forwarder"], scenarioTitle: "Scenario", scenario: "A controlled attack path examines Pass-the-Hash and Kerberoasting as techniques for privilege escalation and lateral movement.", methodTitle: "Detection method", method: "Correlate Windows Security Event ID 4624, 4688, and 4769 to classify unusual network logons, process creation, and Kerberos TGS requests.", findingsTitle: "Evidence", findings: "The use case connects authentication, process, and Kerberos telemetry into a resilient triage foundation rather than relying on a single event.", lessons: ["Review Kerberos TGS requests for unusual encryption and service accounts.", "Evaluate process creation by known attack tools with context.", "Correlate multiple event types and use a baseline for comparison."], tools: ["Wazuh", "Windows Event Viewer", "Splunk", "Wireshark", "PowerShell"] },
      { id: "network-discovery", kind: "Detection engineering case study", title: "Network Discovery Monitoring", lead: "Capture network discovery as behavior: port scanning, service enumeration, and network mapping become testable detection signals.", environment: ["Kali Linux for controlled discovery simulations", "Windows and Linux endpoints", "Wazuh and network telemetry", "Wireshark for packet and context analysis"], scenarioTitle: "Scenario", scenario: "A controlled discovery phase creates repeatable network activity that can be distinguished from normal operations.", methodTitle: "Detection method", method: "Assess timing, target breadth, and port patterns as discovery context, then enrich them with endpoint or network data.", findingsTitle: "Evidence", findings: "The use case shows that a detection’s quality relies on context, a baseline, and triage notes — not only on a single rule.", lessons: ["Evaluate port patterns and target breadth together.", "Include legitimate administrative traffic in the baseline.", "Use packet analysis to enrich log telemetry."], tools: ["Kali Linux", "Wazuh", "Wireshark", "Network Monitoring"] },
      { id: "brute-force", kind: "Blue Team case study", title: "Brute Force Attack Detection", lead: "Detect repeated authentication attempts against SSH, RDP, and web applications through log and behavioral patterns.", environment: ["SSH, RDP, and web authentication sources", "Central log aggregation", "Wazuh for analysis and alerting", "Triage notes for recurring cases"], scenarioTitle: "Scenario", scenario: "Multiple failed authentications are generated as a controlled test case and differentiated from routine error patterns.", methodTitle: "Detection method", method: "Correlate failed attempts, time windows, source-target relationships, and possible subsequent successes.", findingsTitle: "Evidence", findings: "A useful brute-force use case distinguishes failed logon, password spray, and potential successful takeover through the event sequence.", lessons: ["Consider failed attempts and later successful logons together.", "Use time windows and source relationships for prioritisation.", "Document service accounts and admin processes as exceptions."], tools: ["Wazuh", "SSH", "RDP", "Log Analysis"] },
      { id: "powershell", kind: "Endpoint detection case study", title: "Suspicious PowerShell Activity", lead: "Evaluate suspicious PowerShell execution, encoded commands, and unusual module use as an endpoint detection use case.", environment: ["Windows endpoints with PowerShell", "Windows event logs", "Wazuh for centralized telemetry", "Kali Linux for controlled testing"], scenarioTitle: "Scenario", scenario: "PowerShell activity is assessed through its process chain, arguments, and execution context.", methodTitle: "Detection method", method: "Assess encoded arguments, unusual parent-child relationships, and suspicious modules as combined signals.", findingsTitle: "Evidence", findings: "The assessment improves when process context and user relationship are considered together with the command.", lessons: ["Do not evaluate encoded commands in isolation.", "Document the process chain and execution context.", "Include legitimate administration in the baseline."], tools: ["PowerShell", "Windows Event Logs", "Wazuh", "Endpoint Detection"] },
      { id: "ransomware", kind: "Threat detection case study", title: "Ransomware Behavior Detection", lead: "Assess file encryption, registry modification, and unusual network communication as behavioral detection signals.", environment: ["Windows endpoints", "Central log and endpoint telemetry", "Network monitoring", "Incident-response notes"], scenarioTitle: "Scenario", scenario: "A behavioral practice framework connects changes at endpoint and network level into an investigation hypothesis.", methodTitle: "Detection method", method: "Assess file activity, registry traces, process context, and outbound communication for suspicious combinations.", findingsTitle: "Evidence", findings: "Behavioral detection becomes more resilient when several weak signals are linked into a timed sequence.", lessons: ["Correlate file, process, and network traces.", "Document triage steps as part of the use case.", "Account for recovery and escalation paths early."], tools: ["Windows", "Network Monitoring", "Incident Response", "Behavioral Detection"] },
    ],
    writing: { marker: "Lab Notes", heading: ["Notes from the", "lab bench."], intro: "Technical writing that turns experiments into reusable operating knowledge.", items: [{ type: "Lab note / 01", title: "Designing telemetry that stays useful after day one", description: "A practical view of log sources, signal quality, and documenting why an alert exists.", readTime: "6 min read" }, { type: "Detection brief / 02", title: "From ATT&CK technique to a testable detection", description: "A structured flow for turning a behavioral hypothesis into a repeatable homelab exercise.", readTime: "8 min read" }, { type: "Build log / 03", title: "Small SOC labs need intentional boundaries", description: "Notes on segmentation, service ownership, and infrastructure that is easier to investigate.", readTime: "5 min read" }] },
    contact: { eyebrow: "OPEN TO TECHNICAL CONVERSATIONS", heading: ["Make systems", "more visible?"], body: "I welcome conversations about systems integration, security operations, and junior SOC analyst roles. You can also inspect the case studies on GitHub or download the visual portfolio CV.", github: "GitHub profile", linkedin: "LinkedIn profile", cv: "Download portfolio CV", formTitle: "CONTACT / NEW MESSAGE", name: "Name", email: "Email", message: "Message", namePlaceholder: "Your name", emailPlaceholder: "you@company.com", messagePlaceholder: "What would you like to discuss?", submit: "Send message", sending: "Sending …", sent: "Thank you. Your message was sent successfully.", failed: "Your message could not be sent. Please try again or use LinkedIn.", setup: "Formspree is not connected yet. Add the form ID in client/src/config/siteConfig.ts.", privacy: "By submitting, your form data is processed through Formspree.", mailSubjectPrefix: "Portfolio enquiry from", mailBodyName: "Name", mailBodyEmail: "Email", location: "Germany · NRW · Ruhr metropolitan region" },
    footer: { trace: "Signal Trace / SOC Portfolio", back: "Back to top" },
    terminal: { title: "SOC://OPERATOR-SHELL", interactive: "INTERACTIVE", prompt: "marco@soc-lab:~$", placeholder: "Try: about", available: "Commands", soundOn: "Sound on", soundOff: "Sound off", greeting: ["[system] SOC-lab operator connected.", "Type `about`, `stack`, `projects`, `contact`, `help`, or `clear`."], unknown: "Command not found. Type `help` to list available commands.", commands: { about: ["Marco Lütkemüller // Aspiring SOC Analyst.", "Foundation: systems integration, networks, Windows, and Active Directory."], stack: ["Kali Linux · Wazuh · Metasploitable 2/3 · VMware · Windows 10/11", "Status: lab://active"], projects: ["Tracks: SIEM implementation + 5 documented detection case studies."], contact: ["Open GitHub, LinkedIn, or the contact section for technical conversations."], help: ["about — introduction", "stack — homelab stack", "projects — case studies", "contact — contact route", "clear — clear terminal"] } },
  },
} as const;
